name: Validate PR Scope (Super Repo)
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compute changed files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed.txt
          echo "Changed files:" && cat changed.txt
      - name: Enforce scope
        run: |
          ALLOW_RE='^(flow/|docs/|scripts/|docker/|\\.gitmodules$|components/[^/]+$)'
          BAD=0
          while read -r f; do
            if [[ ! $f =~ $ALLOW_RE ]]; then BAD=1; echo "Disallowed path: $f"; fi
          done < changed.txt
          if [[ $BAD -ne 0 ]]; then echo "PR touches files outside allowed scope for super repo"; exit 1; fi
      - name: Require linked PRs for gitlink bumps
        run: |
          if grep -q '^components/' changed.txt; then
            BODY="${{ github.event.pull_request.body }}"
            echo "$BODY" | grep -qi 'Linked PR:' || { echo 'Missing "Linked PR:" in PR body for submodule bump'; exit 1; }
          fi
